INSERT INTO record (record_title, id_genre, id_artist) 
VALUES 
    ('Imagine', 1, 1), 
    ('Kind of Blue', 2, 2), 
    ('Bohemian Rhapsody', 3, 3), 
    ('Symphony No. 5', 4, 4), 
    ('The Thrill Is Gone', 5, 5), 
    ('No Woman No Cry', 7, 6), 
    ('Blue Suede Shoes', 1, 7), 
    ('Space Oddity', 1, 8), 
    ('Smells Like Teen Spirit', 9, 9), 
    ('California Love', 6, 10), 
    ('Thriller', 3, 11), 
    ('Someone Like You', 3, 12), 
    ('Crazy in Love', 11, 13), 
    ('Ring of Fire', 10, 14), 
    ('Shake It Off', 3, 15), 
    ('Purple Haze', 9, 16), 
    ('Respect', 13, 17), 
    ('Purple Rain', 13, 18), 
    ('Lose Yourself', 6, 19), 
    ('Georgia on My Mind', 13, 20), 
    ('Billie Jean', 3, 11), 
    ('Hurt', 10, 14), 
    ('Jailhouse Rock', 1, 7);